# 1. Spring Application 설정
spring:
  application:
    name: user
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        jdbc:
          time_zone: Asia/Seoul

# 2. Eureka 서버의 URL 지정
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL}

service:
  jwt:
    access-expiration: ${JWT_ACCESS_EXPIRATION}
    secret-key: ${JWT_SECRET_KEY}

server:
  port: ${SERVER_PORT}