server:
  port: 19092
spring:
  application:
    name: ai
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ai
    username: postgres
    password: admin1234
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show-sql: true
        format_sql: true
        use_sql_comments: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/
management:
  zipkin:
    tracing:
      endpoint: "http://localhost:9411/api/v2/spans"
  tracing:
    sampling:
      probability: 1.0
service:
  google:
    api:
      key: ${GOOGLE_API_KEY}